openapi: 3.0.3
info:
  title: Mediator Service
  version: 1.0.11
servers:
  - url: http://localhost:9765

paths:
  /get-patient-data:
    post:
      tags:
        - getData
      summary: Patient is requesting for their health records data
      description: Patient will request to see his/her health records.
      operationId: getPatientData
      requestBody:
        description: ABHA ID of the patient will be given. 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getPatientData'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/patientData'
        '404':
          description: ID not available

  /send-patient-data:
    post:
      tags:
        - sendData
      summary: CMS asks Mediator service to send data from destination hospital to source
      description: After approval from patient, CMS will request the Mediator to get data from the destination hospital and send it back to the doctor
      operationId: sendPatientData
      requestBody:
        description: ABHA ID of the patient will be given. 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sendPatientData'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/patientData'
        '404':
          description: Data not available



components:
  schemas:
    getPatientData:
      type: object
      properties:
        ABHA_ID:
          type: string
          format: string
          example: "201822222"
        Doctor_ID:
          type: string
          format: string
          example: "h1_d1"
        Consent_artifact_ID:
          type: string
          format: string
          example: "143"
        QueryParams:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/params'
    params:
      type: object
    
    patientData:
      type: array
      items:
        properties:
          data:
            type: object
            format: healthRecords
            example:
              'blood group' : "b+"
    sendPatientData:
      type: object
      properties:
        ABHA_ID:
          type: string
          format: string
          example: "201822222"
        Doctor_ID:
          type: string
          format: string
          example: "h1_d1"
        consent:
          type: array
          items:
            type: object
            properties:
              category:
                type: string
                format: string
                example: "blood report"
              from:
                type: string
                format: date
                example: '2022-07-01'
              to:
                type: string
                format: date
                example: '2022-07-01'
              hospital:
                type: object
                properties:
                  id:
                    type: string
                    format: string
                    example: "h1"
                  name:
                    type: string
                    format: string
                    example: "hospital 1"
          minItems: 2